#' Package for searching names of plants and their synonyms mentioned in Wildlife (Protection) Act, 1972 (Amended as on date)'
#' @param Userdata Excel file with one sheet and 1 column with heading 'Name' following by rows with species names
#' @author Prakash Pradhan, Purnendu Paul and Md. Maimun Habib
#' @export
#' @examples
#' match_names("Userdata")
#'
match_names <- function() {
  if(!require(readxl)){
    install.packages("readxl")
    library(readxl)
  }
  if(!require(dplyr)){
    install.packages("dplyr")
    library(dplyr)
  }
  if(!require(stringr)){
    install.packages("stringr")
    library(stringr)
  }




  # Load the data from the System File
  WPAdata<-data.frame(Appendix <- c("APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "APPENDIX I ",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "SCHEDULE III",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX II",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III",
                "APPENDIX III"
  ),

  Scientific_Name <- c("Agave parviflora ",
                       "Agave hartmanii",
                       "Pachypodium ambongense",
                       "Pachypodium baronii",
                       "Pachypodium baronii var.baronii  ",
                       "Pachypodium baronii var.erythreum",
                       "Pachypodium decaryi",
                       "Araucaria araucana",
                       "Abies araucana",
                       "Araucaria araucana",
                       "Araucaria araucana subsp. conguillioensis",
                       "Araucaria araucana var. angustifolia",
                       "Araucaria araucana var. aurea",
                       "Araucaria chilensis",
                       "Araucaria dombeyi",
                       "Araucaria imbricata",
                       "Araucaria imbricata var. aurea",
                       "Araucaria imbricata var. platifolia",
                       "Araucaria imbricata var. variegata",
                       "Columbea imbricata",
                       "Columbea imbricata var. densa",
                       "Columbea imbricata var. denudata",
                       "Columbea imbricata var. distans",
                       "Columbea imbricata var. latifolia",
                       "Columbea imbricata var. striata",
                       "Columbea imbricata var. variegata",
                       "Columbea quadrifaria",
                       "Pinus araucana",
                       "Ariocarpus spp. ",
                       "Astrophytum asterias ",
                       "Astrophytum asterias var. magnipunctatum",
                       "Astrophytum asterias var. multipunctatum",
                       "Astrophytum asterias var. nudicarpa",
                       "Astrophytum asterias var. nudum",
                       "Astrophytum asterias var. pubescente",
                       "Astrophytum asterias var. roseiflorum",
                       "Astrophytum asterias var. seminudum",
                       "Echinocactus asterias",
                       "Echinocactus asterias var. nudus",
                       "Aztekium ritteri ",
                       "Echinocactus ritteri",
                       "Coryphantha werdermannii",
                       "Coryphantha werdermannii subsp. unguispina",
                       " Discocactus spp. ",
                       "Echinocereus ferreiranus ssp. Lindsayorum",
                       "Echinocereus ferreiranus var. lindsayorum",
                       "Echinocereus lindsayi",
                       "Echinocereus lindsayorum",
                       " Echinocereus schmollii ",
                       "Cereus schmollii",
                       "Wilcoxia nerispina",
                       "Wilcoxia schmollii",
                       "Wilcoxia schmollii var. lanata",
                       "Escobaria minima ",
                       "Coryphantha minima",
                       "Coryphantha nellieae",
                       "Escobaria nellieae",
                       "Mammillaria nellieae",
                       "Neobesseya minima",
                       "Escobaria sneedii ",
                       "Coryphantha albicolumnaria",
                       "Coryphantha sneedii",
                       "Coryphantha sneedii var. albicolumnaria",
                       "Coryphantha sneedii var. guadalupensis",
                       "Escobaria albicolumnaria",
                       "Escobaria guadalupensis",
                       "Escobaria sneedii subsp. albicolumnaria",
                       "Mammillaria sneedii",
                       "Mammillaria pectinifera (Includes ssp. Solisioidesi)",
                       "Mammillaria pectinifera f. solisioides",
                       "Mammillaria solisioides",
                       "Solisia solisioides",
                       "Melocactus conoideus ",
                       "Melocactus deinacanthus ",
                       "Melocactus glaucescens ",
                       "Melocactus glaucencens",
                       "Melocactus paucispinus ",
                       "Obregonia denegrii ",
                       "Ariocarpus denegrii",
                       "Strombocactus denegrii",
                       "Pachycereus militaris ",
                       "Backebergia militaris",
                       "Backebergia militaris",
                       "Cephalocereus chrysomallus",
                       "Cephalocereus militaris",
                       "Cereus chrysomallus",
                       "Cereus militaris",
                       "Mitrocereus chrysomallus",
                       "Mitrocereus chrysomallus",
                       "Mitrocereus militaris",
                       "Pachycereus chrysomallus",
                       "Pachycereus militaris",
                       "Pilocereus chrysomallus",
                       "Pilocereus militaris",
                       "Pediocactus bradyi ",
                       "Pediocactella bradyi",
                       "Pediocactus simpsonii subsp. bradyi",
                       "Puebloa bradyi (L.D.Benson)",
                       "Toumeya bradyi (L.D.Benson)",
                       "Pediocactus knowltonii ",
                       "Pediocactus bradyi var. knowltonii",
                       "Pediocactus simpsonii var. knowltonii",
                       "Pediocactus paradinei ",
                       "Pediocactus simpsonii var. paradinei",
                       "Pilocanthus paradinei",
                       "Pediocactus peeblesianus ",
                       "Echinocactus peeblesianus",
                       "Navajoa peeblesiana",
                       "Navajoa peeblesiana",
                       "Navajoa peeblesiana",
                       "Navajoa peeblesiana subsp. menzelii",
                       "Neonavajoa peeblesiana",
                       "Pediocactus peeblesianus",
                       "Pediocactus peeblesianus",
                       "Pediocactus peeblesianus var. maianus",
                       "Toumeya peeblesiana",
                       "Utahia peeblesiana",
                       "Pediocactus sileri",
                       "Echinocactus sileri",
                       "Utahia sileri",
                       "Pelecyphora spp. ",
                       "Sclerocactus blainei ",
                       "Pediocactus spinosior subsp. blainei",
                       "Pediocactus spinosior var. schlesseri",
                       "Sclerocactus schlesseri",
                       "Sclerocactus spinosior subsp. blainei",
                       "Sclerocactus spinosior var. blainei",
                       "Sclerocactus spinosior var. schlesseri",
                       "Sclerocactus brevihamatus ssp. tobuschii ",
                       "Ancistrocactus scheeri subsp. tobuschii",
                       "Ancistrocactus tobuschii",
                       "Ferocactus tobuschii",
                       "Mammillaria tobuschii",
                       "Pediocactus brevihamatus subsp. tobuschii",
                       "Ancistrocactus scheeri subsp. tobuschii",
                       "Ancistrocactus tobuschii",
                       "Ferocactus tobuschii",
                       "Mammillaria tobuschii",
                       "Pediocactus brevihamatus subsp. tobuschii",
                       "Sclerocactus brevispinus ",
                       "Pediocactus wetlandicus f. ilseae",
                       "Sclerocactus wetlandicus subsp. ilseae",
                       "Sclerocactus wetlandicus var. ilseae",
                       "Sclerocactus whipplei var. ilseae",
                       "Sclerocactus cloverae ",
                       "Pediocactus cloverae",
                       "Pediocactus cloverae subsp. brackii",
                       "Sclerocactus cloverae subsp. brackii",
                       "Sclerocactus whipplei subsp. cloverae",
                       "Sclerocactus whipplei subvar. aztecia",
                       "Sclerocactus whipplei var. reevesii",
                       "Sclerocactus erectocentrus ",
                       "Echinocactus beguinii",
                       "Echinocactus erectocentrus",
                       "Echinomastus erectocentrus",
                       "Echinomastus erectocentrus subsp. erectocentrus  ",
                       "Gymnocactus beguinii",
                       "Neolloydia beguinii",
                       "Neolloydia erectocentra",
                       "Neolloydia smithii var. beguinii",
                       "Pediocactus erectocentrus",
                       "Sclerocactus johnsonii subsp. erectocentrus",
                       "Thelocactus erectocentrus",
                       "Sclerocactus glaucus ",
                       "Echinocactus glaucus",
                       "Echinocactus glaucus",
                       "Echinocactus subglaucus",
                       "Echinocactus whipplei var. glaucus",
                       "Ferocactus glaucus",
                       "Pediocactus glaucus",
                       "Sclerocactus franklinii",
                       "Sclerocactus whipplei var. glaucus",
                       "Sclerocactus mariposensis ",
                       "Echinomastus mariposensis",
                       "Echinomastus mariposensis subsp. fischeri",
                       "Neolloydia mariposensis",
                       "Pediocactus mariposensis",
                       "Sclerocactus mesae-verdae ",
                       "Coloradoa mesae-verdae",
                       "Echinocactus mesae-verdae",
                       "Ferocactus mesae-verdae",
                       "Pediocactus mesae-verdae",
                       "Sclerocactus nyensis ",
                       "Pediocactus nyensis",
                       "Sclerocactus spinosior subsp. nyensis",
                       "Sclerocactus papyracanthus ",
                       "Echinocactus papyracanthus",
                       "Mammillaria papyracantha",
                       "Pediocactus papyracanthus",
                       "Toumeya papyracantha",
                       "Sclerocactus pubispinus ",
                       "Echinocactus pubispinus",
                       "Ferocactus pubispinus",
                       "Pediocactus pubispinus",
                       "Sclerocactus sileri ",
                       "Pediocactus pubispinus subsp. sileri",
                       "Sclerocactus pubispinus var. sileri",
                       "Sclerocactus wetlandicus ",
                       "Pediocactus wetlandicus",
                       "Sclerocactus glaucus subsp. wetlandicus",
                       "Sclerocactus wrightiae ",
                       "Ferocactus wrightiae",
                       "Pediocactus wrightiae",
                       "Strombocactus spp.",
                       " Turbinicarpus spp.",
                       " Uebelmannia spp.",
                       "Saussurea costus",
                       "Fitzroya cupressoides",
                       "Cupresstellata patagonica",
                       "Fitzroya patagonica",
                       "Libocedrus cupressoides",
                       "Pinus cupressoides",
                       "Pilgerodendron uviferum",
                       "Juniperus uvifera",
                       "Libocedrus tetragona",
                       "Libocedrus uvifera",
                       "Thuja tetragona",
                       "Cycas beddomei",
                       "Cycas circinalis var. beddomei",
                       "Cycas pluma",
                       "Euphorbia ambovombensis",
                       "Euphorbia capsaintemariensis",
                       "Euphorbia cremersii_Includes thefomza viridifolia and the variety rakotozafyi.",
                       "Euphorbia cylindrifolia_Includes the subspecies tuberifera.)",
                       "Euphorbia cylindrifolia subsp.cylindrifolia ",
                       "Euphorbia decaryi (Includes the varieties ampanihyensis, robinsonii and spirosticha).",
                       "Euphorbia francoisii",
                       "Euphorbia francoisii var. francoisii  ",
                       "Euphorbia moratii (Includes the varieties antsingiensis, bemarahensis and multiflora.) ",
                       "Euphorbia parvicyathophora ",
                       "Euphorbia quartziticola ",
                       "Euphorbia tulearensis",
                       "Euphorbia cap-saintemariensis var. tulearensis",
                       "Fouquieria fasciculata ",
                       "Bronnia spinosa",
                       "Fouquieria purpusii",
                       "Aloe albida ",
                       "Aloe kraussii var. minor",
                       "Aloe myriacantha var. minor",
                       "Leptaloe albida",
                       "Aloe albiflora ",
                       "Guillauminia albiflora",
                       "Aloe alfredii ",
                       "Aloe bakeri",
                       "Guillauminia bakeri",
                       " Aloe bellatula ",
                       "Guillauminia bellatula",
                       "Aloe calcairophila ",
                       "Guillauminia calcairophila",
                       "Guillauminia calcairophylla",
                       "Aloe compressa (Includes the varieties paucituberculata, rugosquamosa and schistophila).",
                       "Aloe delphinensis ",
                       "Aloe descoingsii ",
                       "Guillauminia descoingsii",
                       "Aloe fragilis ",
                       "Aloe haworthioides (Includes the variety aurantiaca).",
                       "Aloinella haworthioides",
                       "Lemeea haworthioides",
                       "Aloe helenae ",
                       "Aloe laeta (Includes the variety maniaensis.) ",
                       "Aloe parallelifolia ",
                       "Aloe parvula",
                       "Aloe sempervivoides",
                       "Lemeea parvula",
                       "Aloe pillansii ",
                       "Aloe dichotoma subsp. pillansii",
                       "Aloe pillansii",
                       "Aloe pillansii",
                       "Aloe polyphylla ",
                       "Aloe rauhii ",
                       "Guillauminia rauhii",
                       "Aloe suzannae ",
                       "Aloe versicolor",
                       "Aloe vossii ",
                       "Aerangis ellisii ",
                       "Aerangis alata",
                       "Aerangis buysonii",
                       "Aerangis caulescens",
                       "Aerangis ellisii var. grandiflora",
                       "Aerangis platyphylla",
                       "Angorchis ellisii",
                       "Angraecum buyssonii",
                       "Angraecum dubuyssonii",
                       "Angraecum ellisii",
                       "Cattleya jongheana ",
                       "Bletia jongheana",
                       "Hadrolaelia jongheana",
                       "Laelia jongheana",
                       "Sophronitis jongheana",
                       "Cattleya lobata ",
                       "Bletia boothiana",
                       "Bletia lobata",
                       "Brasilaelia lobata",
                       "Chironiella lobata",
                       "Hadrolaelia lobata",
                       "Laelia boothiana",
                       "Laelia lobata",
                       "Laelia lobata var. alba",
                       "Laelia rivieri",
                       "Sophronitis lobata",
                       "Dendrobium cruentum ",
                       "Callista cruenta",
                       "Mexipedium xerophyticum ",
                       "Paphiopedilum xerophyticum",
                       "Phragmipedium xerophyticum",
                       "Paphiopedilum spp. ",
                       "Peristeria elata ",
                       "Phragmipedium spp. ",
                       "Renanthera imschootiana",
                       "Renanthera papilio",
                       "Dypsis decipiens ",
                       "Chrysalidocarpus decipiens",
                       "Macrophloga decipiens",
                       "Abies guatemalensis ",
                       "Abies guatemalensis subsp. ixtepejiensis",
                       "Abies guatemalensis subsp. longibracteata",
                       "Abies guatemalensis subsp. rushforthii",
                       "Abies guatemalensis subsp. tamaulipasensis",
                       "Abies guatemalensis subsp. zapotekensis",
                       "Abies guatemalensis var. guatemalensis  ",
                       "Abies guatemalensis var. ixtepejiensis",
                       "Abies guatemalensis var. longibracteata",
                       "Abies guatemalensis var. rushforthii",
                       "Abies guatemalensis var. tacanensis",
                       "Abies guatemalensis var. tamaulipasensis",
                       "Abies tacanensis",
                       "Abies zapotekensis",
                       "Podocarpus parlatorei ",
                       "Nageia angustifolia",
                       "Podocarpus angustifolius",
                       "Balmea stormae ",
                       "Sarracenia oreophila ",
                       "Sarracenia rubra ssp. alabamensis ",
                       "Sarracenis rubra ssp. jonesii ",
                       "Sarracenia rubra f. jonesii",
                       "Stangeria eriopus",
                       "Stangeria katzeri",
                       "Stangeria paradoxa",
                       "Stangeria sanderiana",
                       "Stangeria schizodon",
                       "Ceratozamia spp.",
                       " Encephalartos spp. ",
                       "Microcycas calocoma",
                       "Zamia calocoma",
                       " Zamia restrepoi",
                       "Chigua bernalii",
                       "Chigua restrepoi",
                       "Strobilanthes kunthianus",
                       " Coptis teeta",
                       "Coptis teetoides",
                       "Helleborus teeta",
                       "Coscinium fenestratum",
                       "Coscinium maingayi",
                       "Coscinium miosepalum",
                       "Coscinium peltatum",
                       "Coscinium usitatum",
                       "Coscinium wallichianum",
                       "Coscinium wightianum",
                       "Menispermum fenestratum",
                       "Pereiria medica",
                       " Taxus wallichiana",
                       "Cephalotaxus celebica",
                       "Cephalotaxus sumatrana",
                       "Podocarpus celebicus",
                       "Taxus baccata subsp. wallichiana",
                       "Taxus baccata var. wallichiana",
                       "Taxus celebica (Warb.)",
                       "Taxus chinensis var. yunnanensis",
                       "Taxus contorta var. mucronata",
                       "Taxus nucifera",
                       "Taxus obscura",
                       "Taxus orientalis",
                       "Taxus phytonii",
                       "Taxus suffnesii",
                       "Taxus sumatrana subsp. celebica",
                       "Taxus sumatrana subsp. obscura",
                       "Taxus sumatrana subsp. rehderiana",
                       "Taxus wallichiana subsp. yunnanensis (W.C.Cheng & L.K.Fu)",
                       "Taxus wallichiana var. wallichiana",
                       "Taxus wallichiana var. yunnanensis",
                       "Taxus yunnanensis",
                       " Vanda coerulea",
                       "Vanda coerulea f. delicata",
                       "Vanda coerulea f. luwangalba",
                       "Vanda coerulea f. rogersii",
                       "Vanda coerulea var. rogersii",
                       " Nepenthes khasiana",
                       "Nepenthes rubra",
                       "Renanthera imschootiana",
                       "Renanthera papilio",
                       "Cycas spp.",
                       " Ceropegias spp.",
                       " Aenhenrya rotundifolia",
                       "Aenhenrya agastyamalayana",
                       "Anoectochilus rotundifolius",
                       "Odontochilus rotundifolius",
                       " Odontochilus grandiflorus",
                       "Anoectochilus grandiflorus",
                       "Cystopus grandiflorus",
                       "Odontochilus trapterus",
                       " Rhomboda pulchra",
                       "Zeuxine pulchra",
                       " Vrydagzynea viridiflora",
                       " Zeuxine andamanica",
                       " Ipsea malabarica",
                       "Pachystoma malabaricum",
                       "Spathoglottis malabarica",
                       " Habenaria batesii",
                       "Habenaria praetermissa",
                       "Podandriella batesii",
                       " Podophyllum hexandrum",
                       "Dysosma emodi",
                       "Podophyllum emodi",
                       "Podophyllum emodi var. chinense",
                       "Podophyllum emodi var. hexandrum",
                       "Podophyllum hexandrum var. chinense",
                       "Podophyllum sikkimense",
                       "Sinopodophyllum emodi",
                       "Sinopodophyllum hexandrum",
                       "Sinopodophyllum hexandrum var. chinense",
                       "Sinopodophyllum hexandrum var. emodi",
                       "Podophyllum hexandrum",
                       "Dysosma emodi",
                       "Podophyllum emodi",
                       "Podophyllum emodi var. chinense",
                       "Podophyllum emodi var. hexandrum",
                       "Podophyllum hexandrum var. chinense",
                       "Podophyllum sikkimense",
                       "Sinopodophyllum emodi",
                       "Sinopodophyllum hexandrum",
                       "Sinopodophyllum hexandrum var. chinense",
                       "Sinopodophyllum hexandrum var. emodi",
                       " Dolomiaea costus",
                       "Agave victoriae-reginae ",
                       "Nolina interrata",
                       " Yucca queretaroensi",
                       "Agavaceae",
                       "Dracaenaceae",
                       "Eriospermaceae",
                       "Hyacinthaceae",
                       "Galanthus spp. ",
                       "Sternbergia spp.",
                       "Operculicarya decaryi",
                       "Operculicarya hyphaenoides",
                       "Operculicarya pachypus ",
                       "Hoodia spp.",
                       "Pachypodium spp. (Except the species included in Appendix D",
                       "Rauvolfia serpentina ",
                       "Ophioxylon album",
                       "Ophioxylon obversum",
                       "Ophioxylon salutiferum",
                       "Ophioxylon serpentinum",
                       "Ophioxylon trifoliatum",
                       "Rauvolfia obversa",
                       "Rauvolfia serpentina var. obversa",
                       "Rauvolfia trifoliata",
                       "Panax ginseng (Only the population of the Russian Federation; no oilier population is included in the Appendices.)",
                       "Aralia ginseng",
                       "Panax chin-seng",
                       "Panax quinquefolius var. ginseng",
                       "Panax schin-seng var. coraiensis",
                       "Panax verus",
                       "Panax quinquefolius",
                       "Aralia quinquefolia",
                       "Ginseng quinquefolium",
                       "Panax americanus",
                       "Panax americanus var. elatus",
                       "Panax americanus var. obovatus",
                       "Panax cuneatus",
                       "Panax quinquefolius var. americanus",
                       "Panax quinquefolius var. obovatus",
                       "Beaucamea spp. ",
                       "Podophyllum hexandrum",
                       "Dysosma emodi",
                       "Podophyllum emodi",
                       "Podophyllum emodi var. chinense",
                       "Podophyllum emodi var. hexandrum",
                       "Podophyllum hexandrum var. chinense",
                       "Podophyllum sikkimense",
                       "Sinopodophyllum emodi",
                       "Sinopodophyllum hexandrum",
                       "Sinopodophyllum hexandrum var. chinense",
                       "Sinopodophyllum hexandrum var. emodi",
                       "Tillandsia harrisii ",
                       "Tillandsia kammii ",
                       "Tillandsia xerographica",
                       "Tillandsia kruseana",
                       "Tillandsia tomasellii",
                       "Tillandsia xerographica",
                       "CACTACEAE SPP. (Except the species included in Appendix I and except Pereskia spp .. Pereskiopsis spp. and Quiabentia spp.) ",
                       "Caryocar costaricens",
                       "Zygosicyos pubescens",
                       "Zygosicyos pubescens",
                       "Zygosicyos tripartitu",
                       "Widdringtonia whytei",
                       "Callitris whytei",
                       "Widdringtonia nodiflora subsp. whytei",
                       "Widdringtonia nodiflora var. whytei",
                       "Cyathea spp",
                       "CYCADACEAE SPP. (Except the species included in Appendix I)",
                       "Cibotium barometz",
                       "Aspidium barometz",
                       "Balantium glaucescens",
                       "Cibotium djambianum",
                       "Cibotium glaucescens",
                       "Cibotium glaucophyllum",
                       "Dicksonia assamica",
                       "Dicksonia barometz",
                       "Nephrodium barometz",
                       "Polypodium barometz",
                       "Dicksonia spp. (Only the populations of the Americas; no other population is included in the Appendices)",
                       "Dioscorea deltoidea",
                       "Dioscorea deltoidea var. deltoidea  ",
                       "Dioscorea deltoidea var. orbiculata",
                       "Dioscorea nepalensis",
                       "Tamus nepalensis",
                       "Dionaea muscipula",
                       "Dionaea corymbos",
                       "Dionaea sensitiva",
                       "Dionaea sessiliflora",
                       "Dionaea uniflora",
                       "Drosera sessiliflora",
                       "Drosera uniflora",
                       "Diospyros spp",
                       "Fouquieria columnaris",
                       "Fouquieria gigantea",
                       "Idria columnaria",
                       "Oreomunnea pterocarpa",
                       "Engelhardia nicaraguensis",
                       "Engelhardia nicaraguensis",
                       "Engelhardia oreomunnea",
                       "Engelhardia pterocarpa",
                       "Oreamunoa pterocarpa",
                       "Aniba rosaeodora",
                       "Aniba duckei",
                       "Aniba rosaeodora var. amazonica",
                       "Dalbergia spp. (Except for the species listed in Appendix I and Dalbergia · sissoo and Dalbergia latifolia)",
                       " Guibourtia demeusei  ",
                       "Copaifera demeusei",
                       "Copaifera laurentii",
                       "Guibourtia pellegriniana ",
                       "Guibourtia tessmannii ",
                       "Paubrasilia echinata ",
                       "Caesalpinia echinata",
                       "Caesalpinia obliqua",
                       "Guilandina echinata",
                       "Pericopsis elata",
                       " Afrormosia elata ",
                       " Platymiscium parviflorum",
                       "Platymiscium pleiostachyum",
                       " Pterocarpus erinaceus ",
                       "Drepanocarpus senegalensis",
                       "Echinodiscus erinaceus",
                       "Lingoum erinaceum",
                       "Pterocarpus adansonii",
                       "Pterocarpus africanus",
                       "Pterocarpus senegalensis",
                       "Pterocarpus santalinus ",
                       " Lingoum santalinum",
                       "Pterocarpus tinctorius ",
                       "Lingoum tinctorium",
                       "Pterocarpus holtzii",
                       "Pterocarpus kaessneri",
                       "Pterocarpus odoratus",
                       "Pterocarpus stolzii",
                       "Pterocarpus tinctorius var. macrophyllus",
                       "Pterocarpus tinctorius var. odoratus",
                       "Pterocarpus zimmermannii",
                       "Senna meridionalis",
                       "Cassia meridionalis",
                       "Cassia viguierella var. meridionalis",
                       "Aloe spp. (Except the species included in Appendix I. Also excludes Aloe vera, also referenced as Aloe barbadensis which is not included in the Appendices.)",
                       "Adansonia grandidieri",
                       "Cedrela spp. (Populations of the Neotropics)",
                       "Swietenia humilis",
                       "Swietenia bijuga",
                       "Swietenia cirrhata",
                       "Swietenia multijuga",
                       "Swietenia macrophylla (Populations of the Neotropics)",
                       "Swietenia belizensis",
                       "Swietenia candollei",
                       "Swietenia macrophylla var. marabaensis",
                       "Swietenia tessmannii",
                       "Swietenia mahagoni ",
                       "Cedrela mahagoni",
                       "Swietenia acutifolia",
                       "Swietenia fabrilis",
                       "Swietenia mahagoni var. praecociflora",
                       "Swietenia mahogani",
                       "Swietenia mahogoni",
                       "Nepenthes spp. (Except the species included in Appendix I) ",
                       "ORCHIDACEAE SPP.  (Except for the species included in Appendix I)",
                       "Cistanche deserticola",
                       "Cistanche deserticola var. flabellata",
                       "Beccariophoenix madagascariensis",
                       "Dypsis decaryi ",
                       "Neodypsis decaryi",
                       "Lemurophoenix halleuxii ",
                       " Marojejya darianii",
                       "Ravenea louvelii",
                       "Louvelia madagascariensis ",
                       " Ravenea rivularis",
                       " Satranala decussilvae",
                       " Voanioala gerardii",
                       "Adenia firingalavensis",
                       "Adenia firingalavensis var. firingalavensis  ",
                       "Ophiocaulon firingalavense",
                       "Adenia olaboensis",
                       "Adenia olaboensis var. olaboensis  ",
                       "Adenia subsessilifolia ",
                       "Uncarina grandidieri",
                       "Harpagophytum dimidiatum",
                       "Harpagophytum grandidieri",
                       "Uncaria grandidieri",
                       "Uncarina didieri",
                       "Uncarina dimidiata",
                       "Uncarina stellulifera ",
                       "Anacampseros spp.",
                       "Avonia spp. ",
                       "Lewisia serrata",
                       "Cyclamen spp",
                       "Adonis venalis ",
                       "Rothmannia venalis",
                       "Hydrastis canadensis ",
                       "Hydrastis trifolia ",
                       "Warneria canadensis",
                       "Prunus africana",
                       " Pygeum africanum",
                       "Osyris lanceolata (Populations of Burundi, Ethiopia, Kenya, Rwanda, Uganda and the United Republic of Tanzania.)",
                       "Osyris abyssinica",
                       "Osyris arborea",
                       "Osyris arborea var. rotundifolia",
                       "Osyris arborea var. stipitata",
                       "Osyris densifolia",
                       "Osyris divaricata",
                       "Osyris laeta",
                       "Osyris nepalensis",
                       "Osyris oblanceolata",
                       "Osyris parvifolia",
                       "Osyris pendula",
                       "Osyris quadripartita",
                       "Osyris quadripartita var. canariensis",
                       "Osyris rigidissima",
                       "Osyris tenuifolia",
                       "Osyris urundiensis",
                       "Osyris wightiana",
                       "Osyris wightiana var. rotundifolia",
                       "Osyris wightiana var. stipitata",
                       "Sarracenia spp. (Except the species included in Appendix I",
                       "Picrorhiza kurrooa (Excludes Picrorhiza scrophulariiflora) ",
                       "Bowenia spp",
                       "Taxus chinensis  (Includes infraspecific taxa of this species)",
                       "Taxus cuspidata (Includes infraspecific taxa of this species)",
                       "Cephalotaxus umbraculifera",
                       "Taxus baccata subsp. cuspidata",
                       "Taxus baccata var. cuspidata",
                       "Taxus baccata var. latifolia",
                       "Taxus baccata var. microcarpa",
                       "Taxus biternata",
                       "Taxus caespitosa",
                       "Taxus caespitosa var. latifolia",
                       "Taxus cuspidata f. aurescens",
                       "Taxus cuspidata f. densa",
                       "Taxus cuspidata f. fructu-luteo",
                       "Taxus cuspidata f. luteobaccata",
                       "Taxus cuspidata f. minima",
                       "Taxus cuspidata f. thayerae",
                       "Taxus cuspidata subsp. biternata",
                       "Taxus cuspidata var. caespitosa",
                       "Taxus cuspidata var. densa",
                       "Taxus cuspidata var. latifolia",
                       "Taxus cuspidata var. luteobaccata",
                       "Taxus cuspidata var. microcarpa",
                       "Taxus cuspidata var. minima",
                       "Taxus cuspidata var. umbraculifera",
                       "Taxus umbraculifera",
                       "Taxus umbraculifera var. microcarpa",
                       "Taxus Jurana (Includes infraspecific taxa of this species.)",
                       "Taxus sumatrana (Includes infraspecific taxa of this species.)",
                       "Cephalotaxus mannii",
                       "Taxus wallichiana ",
                       "Aquilegia spp.",
                       "Gonystylus spp.",
                       "Gyrinops spp. ",
                       "Cyphostemma elephantopus ",
                       "Cyphostemma laza",
                       "Cyphostemma laza var. laza  ",
                       "Cyphostemma laza var. parvifolia",
                       "Cyphostemma montagnacii",
                       "Welwitschia mirobile",
                       "ZAMIACEAE SPP. (Except the species included in Appendix I) ",
                       "Hedychium philippinense ",
                       "Siphonochilus aethiopicus (Populations of Mozambique, South Africa, Eswatini and Zimbabwe.) ",
                       "Cienkowskia aethiopica",
                       "Cienkowskiella aethiopica",
                       "Cienkowskiella evae",
                       "Kaempferia aethiopica",
                       "Kaempferia aethiopica var. angustifolia",
                       "Kaempferia dewevrei",
                       "Kaempferia ethelae",
                       "Kaempferia evae",
                       "Kaempferia natalensis",
                       "Kaempferia zambeziaca",
                       "Siphonochilus evae",
                       "Siphonochilus natalensis",
                       "Bulnesia sarmientoi ",
                       "Guaiacum spp.",
                       "Quercus mongolica",
                       "Quercus crispula var. manshurica",
                       "Quercus crispulimongolica",
                       "Quercus mongolica f. tomentosa",
                       "Quercus mongolica var. laciniata",
                       "Quercus mongolica var. manshurica (Koidz.)",
                       "Quercus mongolica var. mongolica  ",
                       "Quercus mongolica var. tomentosa",
                       "Quercus mongolica var. typica",
                       "Quercus sessiliflora var. mongolica",
                       "Gnetum montanum",
                       "Gnetum montanum",
                       "Thoa montana",
                       "Dipteryx panamensis",
                       "Magnolia liliifera var. obovata",
                       "Fraxinus mandshurica",
                       "Fraxinus excelsa",
                       "Fraxinus excelsissima",
                       "Fraxinus mammifera",
                       "Fraxinus mandshurica subsp. brevipedicellata",
                       "Fraxinus mandshurica var. japonica",
                       "Fraxinus nigra subsp. mandshurica",
                       "Fraxinus nigra var. mandshurica",
                       "Lodoicea maldivica",
                       "Borassus sonneratii",
                       "Cocos maldivica",
                       "Cocos maritima",
                       "Lodoicea callypige",
                       "Lodoicea sechellarum",
                       "Lodoicea sonneratii",
                       "Meconopsis regia",
                       "Papaver regium",
                       "Pinus koraiensis",
                       "Apinus koraiensis",
                       "Pinus cembra var. excelsa",
                       "Pinus cembra var. mandschurica",
                       "Pinus koraiensis subsp. prokoraiensis",
                       "Pinus mandschurica",
                       "Pinus prokoraiensis",
                       "Pinus strobus",
                       "Strobus koraiensis",
                       "Podocarpus neriifolius",
                       "Margbensonia neriifolia",
                       "Nageia discolor",
                       "Nageia endlicheriana",
                       "Nageia leptostachya",
                       "Nageia neglecta",
                       "Nageia neriifolia",
                       "Podocarpus annamiensis var. hainanensis",
                       "Podocarpus discolor",
                       "Podocarpus endlicherianus",
                       "Podocarpus epiphyticus",
                       "Podocarpus junghuhnianus",
                       "Podocarpus leptostachyus",
                       "Podocarpus macrophyllus var. acuminatissimus",
                       "Podocarpus neriifolius subsp. decipiens",
                       "Podocarpus neriifolius subsp. penibukanensis",
                       "Podocarpus neriifolius subsp. staintonii",
                       "Podocarpus neriifolius var. decipiens",
                       "Podocarpus neriifolius var. linearis",
                       "Podocarpus neriifolius var. membranaceus",
                       "Podocarpus neriifolius var. penibukanensis",
                       "Podocarpus neriifolius var. polyanthus",
                       "Podocarpus neriifolius var. staintonii",
                       "Podocarpus polyanthus (Wasscher)",
                       "Tetracentron sinense",
                       "Tetracentron sinense var. himalense"
  ))
  as_tibble(WPAdata)
  # assigning new names to the columns of the data frame
  colnames(WPAdata) <- c('Appendix','Scientific_Name')
  #summary(WPAdata)
  #WPAdata = read.csv("https://github.com/PradhanP-R/WPAct/blob/main/data/WPA_Plants.csv")
  #load("data/WPAdata.rda")
  Userdata<-read_excel(file.choose())
    #Load user data. It has to be replaced with User Excel
  #Userdata <- data.frame(Name = c("Passiflora indica", "Cryptomeria japonica", "Araucaria imbricata", "Alnus nepalensis", "Wilcoxia nerispina"))
  #as_tibble(Userdata)
  matches <- WPAdata %>%
  semi_join(Userdata, by = c("Scientific_Name" = "Name")) %>%
  select(Appendix, Scientific_Name)
  return(matches)
}
#Userdata <- read_excel("C:/Users/91790/Downloads/WPAplants/R/Test.xlsx", sheet = 1)
#match_names(Testdata)
#Test<-read_excel(file.choose())
#Userdata<-"C:/Users/91790/Downloads/WPAplants/R/Test.xlsx"
match_names()
